---
title: "Assignment 2 - Dynamic Graphs"
author: "Trevor Isaacson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(tidycensus)
library(viridis)
library(plotly)
```

Data: https://www.kaggle.com/datasets/szrlee/stock-time-series-20050101-to-20171231?resource=download

```{r}
stocks = read.csv("Data/all_stocks_2006-01-01_to_2018-01-01.csv")
stocks = stocks %>%
  mutate(Date = as.Date(Date)) %>%
  filter(Name == c("HD", "AAPL", "MSFT", "WMT", "MCD")) %>%
  filter(Date >= "2015-01-01")
head(stocks)

```

```{r}
stocks_plot = ggplot(data = stocks, aes(x=Date, y = Close, color = Name)) +
  geom_line() +
  theme_minimal() +
  scale_x_date(breaks = "1 year", 
               minor_breaks = "1 month",
               date_labels = "%Y",
               limits=c(as.Date("2015-01-01"), NA)) +
  ylab("Closing Price") + xlab("") +
  ggtitle("Stock Information for Several Large Companies") +
  scale_color_viridis(discrete = TRUE) +
  guides(color=guide_legend(title="Ticker"))

volume_plot = ggplot(data = stocks, aes(x=Date, y = Volume/1000000, color = Name)) +
  geom_line() +
  theme_minimal() +
  scale_x_date(breaks = "1 year", 
               minor_breaks = "1 month",
               date_labels = "%Y",
               limits=c(as.Date("2015-01-01"), NA)) +
  ylab("Volume  (in millions)") + xlab("") +
  scale_color_viridis(discrete = TRUE) +
  guides(color=guide_legend(title="Ticker"))

stocks_plotly = ggplotly(stocks_plot) 
volume_plotly = ggplotly(volume_plot)

stocks_plotly
volume_plotly
```


```{r}
stocks_plty_facet <- subplot(list(stocks_plotly,volume_plotly),
                              nrows = 2, 
                              shareX = TRUE,
                              titleX = TRUE) %>%
  rangeslider() %>%
  layout(hovermode = "x")

stocks_plty_facet

```


```{r}
stocks2 = stocks %>%
  filter(Name == "AAPL")
stocks_plty2 = plot_ly(stocks2, x = ~Date) %>%
  add_lines(y = ~Close, name= "Closing Price")
  
volume_plty2 = plot_ly(stocks2, x = ~Date) %>%
  add_lines(y = ~Volume, name = "Volume") 

plty_facet = subplot(list(stocks_plty2, volume_plty2), 
                     nrows = 2, shareX = TRUE, titleX = FALSE) %>%
  rangeslider() %>%
  layout(hovermode = "x") %>%
  layout(
  title="Apple",
  xaxis = list(
    rangeselector = list(
      buttons = list(
        list(
          count = 3,
          label = "3 mo",
          step = "month",
          stepmode = "backward"),
        list(
          count = 6,
          label = "6 mo",
          step = "month",
          stepmode = "backward"),
        list(
          count = 1,
          label = "1 yr",
          step = "year",
          stepmode = "backward"),
        list(step = "all"))),
  rangeslider = list(type = "date")))
                       

plty_facet

```





